"""Tests del parser de formulario, importador de participantes y bracket."""
from __future__ import annotations

from io import BytesIO

import openpyxl
import pytest

from app.services.formulario_parser import parse_formulario
from app.services.participant_import_service import ParticipantImportService
from app.services.tournament_service import TournamentService


def _build_formulario_bytes() -> bytes:
    """Crea un Excel con el mismo layout del 'Formulario apuesta'."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Formulario apuesta"

    # Grupo A (4 equipos, 6 partidos) - encabezado en columna D
    ws["D1"] = "   Grupo A"
    ws["C2"] = "Sentido del marcador >>>>>"
    partidos = [
        ("Mexico", 2, 1, "Sudafrica"),
        ("Corea", 1, 1, "Chequia"),
        ("Chequia", 0, 2, "Sudafrica"),
        ("Mexico", 3, 0, "Corea"),
        ("Sudafrica", 1, 1, "Corea"),
        ("Chequia", 0, 1, "Mexico"),
    ]
    row = 3
    for local, gl, gv, visit in partidos:
        ws[f"C{row}"] = local
        ws[f"D{row}"] = gl
        ws[f"E{row}"] = gv
        ws[f"F{row}"] = visit
        row += 1

    # Bloque de puestos finales
    ws["B20"] = "Puntos Adicionales. >>>>>"
    ws["B21"] = "1 er puesto"
    ws["E21"] = 10
    ws["F21"] = "Mexico"
    ws["B22"] = "2 do puesto"
    ws["E22"] = 9
    ws["F22"] = "Sudafrica"

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


@pytest.fixture()
def formulario_bytes():
    return _build_formulario_bytes()


def test_parse_formulario(formulario_bytes):
    parsed = parse_formulario(formulario_bytes)
    assert len(parsed.matches) == 6
    assert all(m.grupo == "A" for m in parsed.matches)
    assert parsed.matches[0].local == "Mexico"
    assert parsed.matches[0].goles_local == 2
    assert len(parsed.posiciones) == 2
    assert parsed.posiciones[0].posicion == 1
    assert parsed.posiciones[0].equipo == "Mexico"
    assert "Mexico" in parsed.grupos["A"]


def test_import_formulario_creates_everything(db, formulario_bytes):
    result = ParticipantImportService(db).import_formulario(
        formulario_bytes, nombre="German Bello"
    )
    assert result["predicciones_importadas"] == 6
    assert result["partidos_creados"] == 6  # 6 pares (local, visitante) distintos

    from app.repositories.participant_repository import ParticipantRepository
    from app.repositories.position_prediction_repository import (
        PositionPredictionRepository,
    )

    p = ParticipantRepository(db).get(result["participant_id"])
    assert p.nombre == "German Bello"
    positions = PositionPredictionRepository(db).list_for(p.id)
    assert len(positions) == 2
    assert positions[0].equipo == "Mexico"
    assert positions[0].puntos == 10


def test_bracket_predicted_standings(db, formulario_bytes):
    result = ParticipantImportService(db).import_formulario(
        formulario_bytes, nombre="German Bello"
    )
    bracket = TournamentService(db).bracket(participant_id=result["participant_id"])
    grupo_a = next(g for g in bracket["grupos"] if g["grupo"] == "A")
    # México: gana 3 partidos -> debe ir primero en el pronóstico
    assert grupo_a["pronostico"][0]["equipo"] == "Mexico"
    assert bracket["top4"][0]["equipo"] == "Mexico"
    assert len(bracket["clasificados"]) == 2  # top 2 del único grupo


def test_import_email_autogenerated(db, formulario_bytes):
    result = ParticipantImportService(db).import_formulario(
        formulario_bytes, nombre="Juan Pérez"
    )
    from app.repositories.participant_repository import ParticipantRepository

    p = ParticipantRepository(db).get(result["participant_id"])
    assert p.email == "juan.perez@mundial2026.com"
